import {StyleSheet} from 'react-native';
import {Fonts, Colors, FontSize} from 'shared/theme';
import {Metrics, getHeight, getWidth, screenHeight} from 'utils';

export default StyleSheet.create({
  container: {
    flex: 1,
    width: Metrics.screenWidth,
    backgroundColor: '#b57ddc',
  },
  wrapper: {
    flex: 1,
    backgroundColor: '#fbf5ff',
  },
  header: {
    backgroundColor: '#a85fda',
    flexDirection: 'row',
    height: getHeight(55),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logoIcon: {
    justifyContent: 'center',
    alignSelf: 'center',
    width: getHeight(45),
    height: getHeight(45),
    borderRadius: 50,
    alignItems: 'center',
  },
  iconWrapper: {
    width: getWidth(45),
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  backImage: {
    width: getHeight(20),
    height: getHeight(20),
    tintColor: Colors.white,
  },
  welcomeUserWrap: {
    marginTop: getHeight(10),
    paddingHorizontal: getHeight(30),
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'center',
  },
  welcomeText: {
    fontSize: FontSize.xxLarge,
    fontWeight: '700',
    color: '#2c0618',
  },
  userNameText: {
    fontSize: FontSize.xLarge,
    color: '#2c0618',
  },
  card: {
    marginTop: getHeight(10),
    backgroundColor: Colors.white,
    marginHorizontal: getWidth(25),
    marginBottom: getHeight(20),
    borderRadius: 24,
    flex: 1,
    paddingVertical: getHeight(20),
    paddingTop: getHeight(10),
    paddingHorizontal: getHeight(15),
    // height: Metrics.screenHeight - getHeight(120),
    shadowColor: '#2c0618',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  creditBalText: {
    fontSize: FontSize.large,
    fontWeight: '600',
    color: '#2c0618',
    alignSelf: 'center',
  },
  balance: {
    fontSize: getHeight(FontSize.huge),
    color: '#2c0618',
    fontWeight: '700',
    alignSelf: 'center',
  },
  textMessageBal: {
    fontSize: getHeight(FontSize.base),
    color: '#2c0618',
    fontWeight: '500',
    alignSelf: 'center',
  },
  cardBalance: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: getHeight(10),
    backgroundColor: '#fbf5ff',
    marginHorizontal: getWidth(40),
    borderRadius: 50,
    padding: getHeight(10),
    paddingHorizontal: getHeight(30),
    shadowColor: '#2c0618',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8.0,
    elevation: 5,
  },
  loginButton: {
    padding: 0,
    height: getHeight(45),
    borderRadius: 50,
    width: getHeight(50),
    marginHorizontal: getHeight(0),
    backgroundColor: '#691aa0',
    paddingHorizontal: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  walletInfo: {
    fontSize: FontSize.base,
    color: '#2c0618',
    fontWeight: '600',
    lineHeight: getHeight(28),
  },
  walletDesInfo: {
    fontSize: FontSize.small,
    color: '#2c0618',
    paddingHorizontal: 16,
  },
  btnText: {
    alignSelf: 'center',
    fontWeight: '700',
    fontSize: FontSize.xSmall,
  },
  descriptionWrap: {
    marginTop: getHeight(100),
  },
  infoIcon: {
    width: getHeight(20),
    height: getHeight(20),
  },
  inputContainer: {
    paddingHorizontal: getHeight(10),
    marginTop: getHeight(14),
    minHeight: getHeight(60),
    maxHeight: getHeight(100),
    borderRadius: 20,
    borderWidth: 0.5,

    borderColor: '#b57ddc',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  input: {
    color: '#691aa0',
    fontWeight: '500',
    opacity: 0.9,
    marginHorizontal: getWidth(8),
    //width: getWidth(210),
    paddingVertical: getHeight(6),
    alignSelf: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    fontSize: FontSize.base,
  },
  messageText: {
    fontSize: getHeight(FontSize.mediumlarge),
    color: '#2c0618',
  },
  messageWrapper: {
    backgroundColor: '#c1a0d8',
    marginVertical: 3,
    padding: 4,
    paddingHorizontal: getHeight(12),
    borderRadius: 8,
  },
  chatText: {
    fontSize: FontSize.large,
    color: '#2c0618',
    alignSelf: 'center',
    top: -getHeight(5),
    fontWeight: '700',
  },
  // msgArea: {height: getHeight(100)},
  sendImage: {
    width: getHeight(25),
    height: getHeight(25),
    tintColor: Colors.white,
    marginLeft: -2,
    marginTop: -2,
  },
  deleteContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: getWidth(20),
    marginTop: 8,
  },
  deleteButton: {
    padding: 0,
    height: getHeight(30),
    borderRadius: 50,
    marginHorizontal: getHeight(0),
    paddingHorizontal: getWidth(25),
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelText: {
    color: Colors.black,
    fontSize: FontSize.mediumSmall,
  },
  deleteText: {
    color: 'white',
    fontSize: FontSize.mediumSmall,
  },
});
