import {StyleSheet} from 'react-native';
import {Fonts, Colors, FontSize} from 'shared/theme';
import {Metrics, getHeight, getWidth} from 'utils';

export default StyleSheet.create({
  container: {
    flex: 1,
    width: Metrics.screenWidth,
    backgroundColor: '#b57ddc',
  },
  wrapper: {
    flex: 1,
    backgroundColor: '#fbf5ff',
  },
  header: {
    backgroundColor: '#a85fda',
    flexDirection: 'row',
    height: getHeight(55),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logoutStyle: {
    color: Colors.white,
    paddingRight: 4,
  },
  logoIcon: {
    justifyContent: 'center',
    alignSelf: 'center',
    width: getHeight(45),
    height: getHeight(45),
    borderRadius: 50,
    alignItems: 'center',
  },
  iconWrapper: {
    width: getWidth(65),
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  backImage: {
    width: getHeight(20),
    height: getHeight(20),
    tintColor: Colors.white,
  },
  welcomeUserWrap: {
    marginTop: getHeight(30),
    paddingHorizontal: getHeight(30),
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  welcomeText: {
    fontSize: FontSize.xxLarge,
    fontWeight: '700',
    color: '#2c0618',
  },
  userNameText: {
    fontSize: FontSize.xLarge,
    color: '#2c0618',
  },
  card: {
    marginTop: getHeight(25),
    backgroundColor: Colors.white,
    marginHorizontal: getWidth(15),
    borderRadius: 24,
    padding: getHeight(30),
    paddingTop: getHeight(20),
    shadowColor: '#2c0618',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  creditBalText: {
    fontSize: FontSize.large,
    fontWeight: '600',
    color: '#2c0618',
    alignSelf: 'center',
  },
  balance: {
    fontSize: FontSize.huge,
    color: '#2c0618',
    fontWeight: '700',
    alignSelf: 'center',
  },
  cardBalance: {
    marginTop: getHeight(30),
    backgroundColor: '#fbf5ff',
    marginHorizontal: getWidth(60),
    borderRadius: 50,
    padding: getHeight(20),
    shadowColor: '#2c0618',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8.0,
    elevation: 5,
  },
  askNowButton: {
    backgroundColor: Colors.white,
    marginVertical: getHeight(40),
    padding: getHeight(16),
    alignItems: 'center',
    borderRadius: 40,
    shadowColor: '#2c0618',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    width: getWidth(150),
    shadowOpacity: 0.2,
    shadowRadius: 8.0,
    elevation: 5,
  },
  askText: {
    alignSelf: 'center',
    color: '#691aa0',
    fontWeight: '700',
    fontSize: getWidth(FontSize.base),
  },
  btnConatiner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: getWidth(25),
  },
  loginButton: {
    marginTop: getHeight(30),
    height: getHeight(60),
    borderRadius: 50,
    marginHorizontal: getHeight(12),
    backgroundColor: '#691aa0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  walletInfo: {
    fontSize: FontSize.base,
    color: '#2c0618',
    fontWeight: '600',
    lineHeight: getHeight(28),
  },
  walletDesInfo: {
    fontSize: FontSize.small,
    color: '#2c0618',
    paddingHorizontal: 16,
  },
  input: {
    color: '#691aa0',
    fontWeight: '500',
    opacity: 0.9,
    padding: 0,
    height: getHeight(30),
    fontSize: FontSize.base,
  },
  inputContainer: {
    paddingHorizontal: getHeight(20),
    marginTop: getHeight(14),
    height: getHeight(50),
    borderRadius: 50,
    borderWidth: 0.5,
    borderColor: '#b57ddc',
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: getHeight(0),
  },
  btnText: {
    alignSelf: 'center',
    fontWeight: '700',
    fontSize: FontSize.large,
  },
  descriptionWrap: {
    marginTop: getHeight(20),
  },
  infoIcon: {
    width: getHeight(20),
    height: getHeight(20),
  },
  tw: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: getHeight(20),
  },
  tc: {
    marginVertical: getHeight(5),
    marginHorizontal: getWidth(5),
    width: getWidth(60),
    padding: getHeight(5),
    alignItems: 'center',
    borderRadius: 40,
    shadowColor: '#691aa0',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8.0,
    elevation: 5,
  },
});
